# Generated by Django 3.2.4 on 2021-06-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf_mc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_m', models.CharField(max_length=40)),
                ('pdf_m', models.FileField(blank=True, null=True, upload_to='media/pdfs/')),
            ],
        ),
    ]
